version: '3.8'

services:

  webapp-birdnest:
    container_name: webapp-birdnest
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - webapp-hlepik-volume:/app/wwwroot/uploads
      - static-volume:/app/content/uploads
    extra_hosts:
      - "host.docker.internal:host-gateway"
    restart: on-failure
    environment:
      ASPNETCORE_ENVIRONMENT: "Development"
      ConnectionStrings__DefaultConnection: "Server=hlepik-birdnest.postgres.database.azure.com;Database=birdnest-hlepik;Port=5432;User Id=hlepik;Password=Birdnest123;Ssl Mode=VerifyFull;"
    ports:
      - "18080:80"

#  birdnest-hlepik:
#    container_name: "birdnesthlepik"
#    build:
#      context: ./Frontend
#      dockerfile: Dockerfile-front
#    restart: on-failure
#    ports:
#      # this maps external:internal, but the docker created network between images is connected directly - using the original ports
#      # so use external for connecting with admin tools - docker will forward connection to internal port
#      - "5000:5000"

volumes:
  webapp-birdnest-volume:
  static-volume:
