# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy container app to Azure Web App - birdnest-hlepik

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: 'ubuntu-latest'

    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Log in to registry
      uses: docker/login-action@v1
      with:
        registry: https://hlepik.azurecr.io/
        username: ${{ secrets.AzureAppService_ContainerUsername_abff2577756f46f9812e8416fe0d139b }}
        password: ${{ secrets.AzureAppService_ContainerPassword_e5c89392868346e48982e52a979ea8bd }}

    - name: Build and push container image to registry
      uses: docker/build-push-action@v2
      with:
        push: true
        tags: hlepik.azurecr.io/${{ secrets.AzureAppService_ContainerUsername_abff2577756f46f9812e8416fe0d139b }}/birdnest3:${{ github.sha }}
        file: ./Dockerfile

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
    - name: Deploy to Azure Web App
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'birdnest-hlepik'
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_b99a4ba940f94eec87b3cf6f1cd2aa49 }}
        images: 'hlepik.azurecr.io/${{ secrets.AzureAppService_ContainerUsername_abff2577756f46f9812e8416fe0d139b }}/birdnest3:${{ github.sha }}'